/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package default_package;
import javax.swing.*;
import java.util.*;
import java.awt.*;
/**
 *
 * @author lx_user
 */
public class MetroGUI extends javax.swing.JFrame {

    /**
     * Creates new form SimpleAppForm
     */
    public MetroGUI() {
        getContentPane().setBackground(new Color(51,59,84));            //set background color
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Graph = new javax.swing.JPanel();
        FunctionField = new javax.swing.JTextField();
        PlotButton = new javax.swing.JPanel();
        Plot = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metro Plotter");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(56, 69, 98));
        setForeground(java.awt.Color.lightGray);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        Graph.setBackground(new java.awt.Color(51, 59, 84));
        Graph.setForeground(new java.awt.Color(255, 255, 255));
        Graph.setPreferredSize(new java.awt.Dimension(706, 706));

        javax.swing.GroupLayout GraphLayout = new javax.swing.GroupLayout(Graph);
        Graph.setLayout(GraphLayout);
        GraphLayout.setHorizontalGroup(
            GraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        GraphLayout.setVerticalGroup(
            GraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );

        FunctionField.setBackground(new java.awt.Color(51, 59, 84));
        FunctionField.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        FunctionField.setForeground(new java.awt.Color(255, 118, 188));
        FunctionField.setText("  function goes here");
        FunctionField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 118, 188), 1, true));
        FunctionField.setCaretColor(new java.awt.Color(86, 197, 255));
        FunctionField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        FunctionField.setMargin(new java.awt.Insets(50, 50, 50, 50));
        FunctionField.setSelectionColor(new java.awt.Color(51, 51, 51));
        FunctionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FunctionFieldActionPerformed(evt);
            }
        });

        PlotButton.setBackground(new java.awt.Color(0, 203, 155));
        PlotButton.setForeground(new java.awt.Color(0, 203, 155));
        PlotButton.setToolTipText("Press to plot");
        PlotButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PlotButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlotButtonMouseClicked(evt);
            }
        });

        Plot.setAlignment(java.awt.Label.CENTER);
        Plot.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        Plot.setForeground(new java.awt.Color(235, 240, 241));
        Plot.setText("plot");
        Plot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlotMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PlotButtonLayout = new javax.swing.GroupLayout(PlotButton);
        PlotButton.setLayout(PlotButtonLayout);
        PlotButtonLayout.setHorizontalGroup(
            PlotButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlotButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Plot, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        PlotButtonLayout.setVerticalGroup(
            PlotButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlotButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Plot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(51, 59, 84));

        jLabel1.setBackground(new java.awt.Color(51, 59, 84));
        jLabel1.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 118, 188));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("y =");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FunctionField, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PlotButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Graph, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FunctionField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PlotButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        Graph.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlotButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlotButtonMouseClicked
        FunctionPanel.resize = true;
        Main.mainLoop(FunctionField.getText());
        FunctionPanel.resize = false;
    }//GEN-LAST:event_PlotButtonMouseClicked

    private void FunctionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FunctionFieldActionPerformed
        
    }//GEN-LAST:event_FunctionFieldActionPerformed

    private void PlotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlotMouseClicked
        PlotButtonMouseClicked(evt);
    }//GEN-LAST:event_PlotMouseClicked

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        PlotButtonMouseClicked(null);
    }//GEN-LAST:event_formComponentResized

    public static MetroGUI getWindow(){
        return window;
    }
    public JTextField getFunctionField(){
        return FunctionField;
    }
    public JPanel getGraph(){
        return Graph;
    }
    public JPanel getPlotButton(){
        return PlotButton;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                window = new MetroGUI();
                window.Graph.setLayout(new BorderLayout());
                window.Graph.add(new FunctionPanel(),BorderLayout.CENTER);
                window.pack();
                window.setVisible(true);
            }
        });
    }
    public static MetroGUI window;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FunctionField;
    private javax.swing.JPanel Graph;
    private java.awt.Label Plot;
    private javax.swing.JPanel PlotButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
